#!/bin/bash
pid=$(ps -ef | grep "[4]-to_infinity_and_beyond" | awk '{print $2}')

if [ -n "$pid" ]; then
  kill "$pid"
  echo "✅ Process $pid terminated."
else
  echo "⚠️ No matching process found."
fi
